# Generated by Django 4.2.7 on 2026-02-22 03:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "sales_management",
            "0005_detalleventa_aplica_iva_detalleventa_monto_iva_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SRIConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "api_token",
                    models.CharField(
                        help_text="Token vsr_XXXXX otorgado por APIVendo",
                        max_length=255,
                    ),
                ),
                (
                    "is_test_mode",
                    models.BooleanField(
                        default=True,
                        help_text="Si está activo, usa el ambiente de pruebas",
                    ),
                ),
                (
                    "api_url",
                    models.URLField(
                        default="https://apivendo.fronteratech.ec/api/sri/documents/create_and_process_invoice_complete/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Configuración SRI",
                "verbose_name_plural": "Configuraciones SRI",
            },
        ),
        migrations.CreateModel(
            name="SRILog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_data", models.JSONField()),
                ("response_data", models.JSONField(blank=True, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("message", models.TextField(blank=True)),
                ("invoice_id_apivendo", models.IntegerField(blank=True, null=True)),
                ("invoice_number_sri", models.CharField(blank=True, max_length=50)),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sri_logs",
                        to="sales_management.venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log SRI",
                "verbose_name_plural": "Logs SRI",
                "ordering": ["-fecha_envio"],
            },
        ),
    ]
