# Generated by Django 4.2.7 on 2025-10-24 03:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system_configuration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuracionsistema",
            name="ambiente_facturacion",
        ),
        migrations.RemoveField(
            model_name="configuracionsistema",
            name="certificado_digital_path",
        ),
        migrations.RemoveField(
            model_name="configuracionsistema",
            name="clave_certificado",
        ),
        migrations.RemoveField(
            model_name="configuracionsistema",
            name="facturacion_electronica_activa",
        ),
    ]
