# Generated by Django 4.2.7 on 2025-10-24 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "system_configuration",
            "0002_remove_configuracionsistema_ambiente_facturacion_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuracionsistema",
            name="iva_default",
        ),
        migrations.AddField(
            model_name="configuracionsistema",
            name="iva_activo",
            field=models.BooleanField(
                default=True, help_text="Activar cálculo automático de IVA en ventas"
            ),
        ),
        migrations.AddField(
            model_name="configuracionsistema",
            name="porcentaje_iva",
            field=models.DecimalField(
                decimal_places=2,
                default=15.0,
                help_text="Porcentaje de IVA (%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
