# Generated by Django 4.2.7 on 2025-10-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "system_configuration",
            "0003_remove_configuracionsistema_iva_default_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="healthcheck",
            name="uso_cpu_porcentaje",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Porcentaje de uso de CPU",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="healthcheck",
            name="uso_disco_porcentaje",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Porcentaje de uso del disco",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="healthcheck",
            name="espacio_disco_libre_gb",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Espacio libre en disco en GB",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="healthcheck",
            name="uso_memoria_porcentaje",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Porcentaje de uso de memoria RAM",
                max_digits=5,
                null=True,
            ),
        ),
    ]
