# Generated by Django 4.2.7 on 2025-10-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_management", "0002_cliente_detalleventa_devolucion_pago_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="numero_venta",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Número único de venta (VNT-2025-00001)",
                max_length=20,
                unique=True,
            ),
        ),
    ]
