# Generated by Django 4.2.7 on 2025-10-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_management", "0003_alter_venta_numero_venta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devolucion",
            name="descripcion",
            field=models.TextField(
                help_text="Descripción detallada del motivo de devolución"
            ),
        ),
    ]
