# Generated by Django 4.2.7 on 2025-10-24 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_management", "0005_alter_quintal_options_and_more"),
        ("sales_management", "0004_alter_devolucion_descripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleventa",
            name="aplica_iva",
            field=models.BooleanField(
                default=False,
                help_text="Indica si este producto graba IVA (copiado de producto al momento de la venta)",
            ),
        ),
        migrations.AddField(
            model_name="detalleventa",
            name="monto_iva",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monto de IVA calculado para este item",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="porcentaje_iva_aplicado",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Porcentaje de IVA aplicado al momento de la venta (%)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="precio_por_unidad_peso",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Precio por unidad de peso al momento de la venta (SIN IVA)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="precio_unitario",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio por unidad al momento de la venta (SIN IVA)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="detalles_venta",
                to="inventory_management.producto",
            ),
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Monto ANTES del descuento (SIN IVA)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Monto DESPUÉS del descuento + IVA",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="descuento",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Descuento adicional a nivel de venta",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="impuestos",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monto total de IVA calculado",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Suma de subtotales de detalles (SIN IVA, después de descuentos por item)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total final = subtotal - descuento + impuestos",
                max_digits=10,
            ),
        ),
        migrations.AddIndex(
            model_name="detalleventa",
            index=models.Index(
                fields=["aplica_iva"], name="sales_detal_aplica__cf1b39_idx"
            ),
        ),
    ]
