# Generated by Django 4.2.7 on 2026-04-07 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "sales_management",
            "0005_detalleventa_aplica_iva_detalleventa_monto_iva_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venta",
            name="factura_electronica_clave",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="factura_electronica_enviada",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="factura_electronica_xml",
        ),
    ]
