# Generated by Django 4.2.7 on 2025-10-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="iva",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Porcentaje de IVA aplicado (%)",
                max_digits=5,
            ),
        ),
    ]
