# Generated by Django 4.2.7 on 2025-10-24 04:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_management", "0003_agregar_marca"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="iva",
        ),
    ]
