# Generated by Django 4.2.7 on 2025-10-24 06:17

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory_management", "0004_remove_producto_iva"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quintal",
            options={
                "ordering": ["fecha_ingreso"],
                "verbose_name": "Quintal",
                "verbose_name_plural": "Quintales",
            },
        ),
        migrations.RemoveIndex(
            model_name="quintal",
            name="inv_quintal_codigo__66273c_idx",
        ),
        migrations.RemoveIndex(
            model_name="quintal",
            name="inv_quintal_product_c461f4_idx",
        ),
        migrations.RenameField(
            model_name="quintal",
            old_name="fecha_recepcion",
            new_name="fecha_ingreso",
        ),
        migrations.RemoveField(
            model_name="detallecompra",
            name="fecha_recepcion",
        ),
        migrations.RemoveField(
            model_name="detallecompra",
            name="quintal_creado",
        ),
        migrations.RemoveField(
            model_name="detallecompra",
            name="recibido",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="precio_unitario",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="proveedor",
        ),
        migrations.RemoveField(
            model_name="quintal",
            name="codigo_unico",
        ),
        migrations.RemoveField(
            model_name="quintal",
            name="lote_proveedor",
        ),
        migrations.RemoveField(
            model_name="quintal",
            name="numero_factura_compra",
        ),
        migrations.RemoveField(
            model_name="quintal",
            name="origen",
        ),
        migrations.AddField(
            model_name="producto",
            name="aplica_impuestos",
            field=models.BooleanField(
                default=True,
                help_text="¿Este producto grava IVA? El porcentaje se obtiene de Configuración del Sistema",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="precio_venta",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio de venta por unidad - Para productos normales (SIN IVA)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="quintal",
            name="codigo_quintal",
            field=models.CharField(
                db_index=True,
                default="TEMP-00000",
                help_text="Código único del quintal (ej: QNT-00001)",
                max_length=20,
                unique=False,
                null=True,
                blank=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quintal",
            name="compra",
            field=models.ForeignKey(
                blank=True,
                help_text="Compra asociada a este quintal",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quintales",
                to="inventory_management.compra",
            ),
        ),
        migrations.AddField(
            model_name="unidadmedida",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="compra",
            name="usuario_recepcion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compras_recibidas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="detallecompra",
            name="cantidad_unidades",
            field=models.IntegerField(
                blank=True,
                help_text="Cantidad de unidades (para productos normales)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="detallecompra",
            name="costo_unitario",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Costo unitario o por unidad de peso",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="detallecompra",
            name="peso_comprado",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Peso comprado (para quintales)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="detallecompra",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, help_text="Subtotal de esta línea", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="compra",
            field=models.ForeignKey(
                blank=True,
                help_text="Referencia a compra",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory_management.compra",
            ),
        ),
        migrations.AlterField(
            model_name="movimientoquintal",
            name="tipo_movimiento",
            field=models.CharField(
                choices=[
                    ("ENTRADA", "📥 Entrada inicial (recepción)"),
                    ("SALIDA", "📤 Salida por venta"),
                    ("AJUSTE_ENTRADA", "➕ Ajuste positivo (corrección suma)"),
                    ("AJUSTE_SALIDA", "➖ Ajuste negativo (corrección resta)"),
                    ("MERMA", "💔 Merma/Pérdida"),
                    ("ENTRADA_DEVOLUCION", "↩️ Entrada por devolución"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio_por_unidad_peso",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio por unidad de peso (ej: $2.50/lb) - Para quintales",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="quintal",
            name="estado",
            field=models.CharField(
                choices=[
                    ("DISPONIBLE", "🟢 Disponible - Tiene peso disponible"),
                    ("RESERVADO", "🟡 Reservado - En proceso de venta"),
                    ("AGOTADO", "⚫ Agotado - Peso en cero"),
                ],
                db_index=True,
                default="DISPONIBLE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="quintal",
            name="proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quintales",
                to="inventory_management.proveedor",
            ),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(
                fields=["aplica_impuestos", "activo"],
                name="inv_product_aplica__9d6dbb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quintal",
            index=models.Index(
                fields=["codigo_quintal"], name="inv_quintal_codigo__cdf09a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quintal",
            index=models.Index(
                fields=["producto", "estado", "fecha_ingreso"],
                name="inv_quintal_product_3de85f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quintal",
            index=models.Index(
                fields=["fecha_vencimiento"], name="inv_quintal_fecha_v_1cef29_idx"
            ),
        ),
    ]
