# Generated by Django 4.2.7 on 2025-10-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_management", "0005_alter_quintal_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quintal",
            name="codigo_quintal",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Código único del quintal (ej: QNT-00001)",
                max_length=20,
                unique=True,
            ),
        ),
    ]
