# Generated by Django 4.2.7 on 2026-01-13 22:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_management", "0006_alter_quintal_codigo_quintal"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="cantidad_quintales",
            field=models.IntegerField(
                default=0, help_text="Cantidad total de quintales disponibles"
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="stock_total_calculado",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                help_text="Suma total de peso de todos los quintales disponibles",
                max_digits=12,
            ),
        ),
    ]
