# Generated by Django 4.2.7 on 2025-10-02 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SnapshotDashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fecha_snapshot",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "total_ventas_dia",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_ventas_mes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("numero_ventas_dia", models.IntegerField(default=0)),
                ("numero_ventas_mes", models.IntegerField(default=0)),
                (
                    "valor_inventario_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("productos_criticos", models.IntegerField(default=0)),
                ("productos_agotados", models.IntegerField(default=0)),
                (
                    "efectivo_en_caja",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "metricas_completas",
                    models.JSONField(
                        default=dict, help_text="Todas las métricas del dashboard"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("AUTOMATICO", "Automático (cada hora)"),
                            ("CIERRE_DIA", "Cierre de día"),
                            ("MANUAL", "Manual"),
                        ],
                        default="AUTOMATICO",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot de Dashboard",
                "verbose_name_plural": "Snapshots de Dashboard",
                "db_table": "rpt_snapshot_dashboard",
                "ordering": ["-fecha_snapshot"],
                "indexes": [
                    models.Index(
                        fields=["-fecha_snapshot"],
                        name="rpt_snapsho_fecha_s_9da128_idx",
                    ),
                    models.Index(
                        fields=["tipo", "-fecha_snapshot"],
                        name="rpt_snapsho_tipo_45a326_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReporteGuardado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo del reporte", max_length=200
                    ),
                ),
                (
                    "tipo_reporte",
                    models.CharField(
                        choices=[
                            ("VENTAS_DIARIAS", "Ventas Diarias"),
                            ("VENTAS_MENSUALES", "Ventas Mensuales"),
                            ("INVENTARIO_VALORIZADO", "Inventario Valorizado"),
                            ("RENTABILIDAD_PRODUCTOS", "Rentabilidad por Producto"),
                            ("MOVIMIENTOS_CAJA", "Movimientos de Caja"),
                            ("TRAZABILIDAD_QUINTALES", "Trazabilidad de Quintales"),
                            ("PRODUCTOS_CRITICOS", "Productos Críticos"),
                            ("COMPARATIVO_PERIODOS", "Comparativo entre Períodos"),
                            ("ARQUEOS_CAJA", "Arqueos de Caja"),
                            ("ANALISIS_CLIENTES", "Análisis de Clientes"),
                            ("VENTAS_POR_VENDEDOR", "Ventas por Vendedor"),
                            ("DASHBOARD_EJECUTIVO", "Dashboard Ejecutivo"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("fecha_desde", models.DateField()),
                ("fecha_hasta", models.DateField()),
                (
                    "filtros",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Filtros aplicados en formato JSON",
                    ),
                ),
                (
                    "datos",
                    models.JSONField(
                        default=dict, help_text="Datos calculados del reporte"
                    ),
                ),
                (
                    "resumen",
                    models.TextField(
                        blank=True, help_text="Resumen ejecutivo del reporte"
                    ),
                ),
                (
                    "formato",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("EXCEL", "Excel"),
                            ("CSV", "CSV"),
                            ("JSON", "JSON"),
                        ],
                        default="PDF",
                        max_length=10,
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True, null=True, upload_to="reportes/%Y/%m/"
                    ),
                ),
                (
                    "fecha_generacion",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reportes_generados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte Guardado",
                "verbose_name_plural": "Reportes Guardados",
                "db_table": "rpt_reporte_guardado",
                "ordering": ["-fecha_generacion"],
                "indexes": [
                    models.Index(
                        fields=["tipo_reporte", "-fecha_generacion"],
                        name="rpt_reporte_tipo_re_0e4033_idx",
                    ),
                    models.Index(
                        fields=["usuario", "-fecha_generacion"],
                        name="rpt_reporte_usuario_cc7bad_idx",
                    ),
                    models.Index(
                        fields=["fecha_desde", "fecha_hasta"],
                        name="rpt_reporte_fecha_d_2d2e49_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionReporte",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_reporte",
                    models.CharField(
                        choices=[
                            ("VENTAS_DIARIAS", "Ventas Diarias"),
                            ("VENTAS_MENSUALES", "Ventas Mensuales"),
                            ("INVENTARIO_VALORIZADO", "Inventario Valorizado"),
                            ("RENTABILIDAD_PRODUCTOS", "Rentabilidad por Producto"),
                            ("MOVIMIENTOS_CAJA", "Movimientos de Caja"),
                            ("TRAZABILIDAD_QUINTALES", "Trazabilidad de Quintales"),
                            ("PRODUCTOS_CRITICOS", "Productos Críticos"),
                            ("COMPARATIVO_PERIODOS", "Comparativo entre Períodos"),
                            ("ARQUEOS_CAJA", "Arqueos de Caja"),
                            ("ANALISIS_CLIENTES", "Análisis de Clientes"),
                            ("VENTAS_POR_VENDEDOR", "Ventas por Vendedor"),
                            ("DASHBOARD_EJECUTIVO", "Dashboard Ejecutivo"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "nombre_configuracion",
                    models.CharField(
                        help_text="Nombre para identificar esta configuración",
                        max_length=100,
                    ),
                ),
                (
                    "configuracion",
                    models.JSONField(
                        default=dict, help_text="Filtros, columnas, formatos preferidos"
                    ),
                ),
                ("es_predeterminada", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuraciones_reportes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Reporte",
                "verbose_name_plural": "Configuraciones de Reportes",
                "db_table": "rpt_configuracion_reporte",
                "unique_together": {
                    ("usuario", "tipo_reporte", "nombre_configuracion")
                },
            },
        ),
    ]
