# Generated by Django 4.2.7 on 2026-04-07 20:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sales_management", "0006_remove_venta_factura_electronica_clave_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificadoDigital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to="sri/certificados/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["p12"]
                            )
                        ],
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        help_text="Contraseña de la firma electrónica", max_length=255
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Certificado Digital",
                "verbose_name_plural": "Certificados Digitales",
            },
        ),
        migrations.CreateModel(
            name="SRIConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ambiente",
                    models.IntegerField(
                        choices=[(1, "Pruebas"), (2, "Producción")], default=1
                    ),
                ),
                (
                    "tipo_emision",
                    models.IntegerField(choices=[(1, "Emisión Normal")], default=1),
                ),
                (
                    "ruc",
                    models.CharField(
                        help_text="RUC de la empresa (13 dígitos)", max_length=13
                    ),
                ),
                ("razon_social", models.CharField(max_length=300)),
                (
                    "nombre_comercial",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("direccion_matriz", models.TextField()),
                ("obligado_contabilidad", models.BooleanField(default=True)),
                (
                    "contribuyente_especial",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "agente_retencion",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("regimen_microempresas", models.BooleanField(default=False)),
                ("regimen_rimpe", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Configuración SRI",
                "verbose_name_plural": "Configuraciones SRI",
            },
        ),
        migrations.CreateModel(
            name="PuntoEmision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "establecimiento",
                    models.CharField(help_text="Ej: 001", max_length=3),
                ),
                ("punto_emision", models.CharField(help_text="Ej: 001", max_length=3)),
                ("direccion_establecimiento", models.TextField()),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Punto de Emisión",
                "verbose_name_plural": "Puntos de Emisión",
                "unique_together": {("establecimiento", "punto_emision")},
            },
        ),
        migrations.CreateModel(
            name="ComprobanteElectronico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "clave_acceso",
                    models.CharField(blank=True, max_length=49, null=True, unique=True),
                ),
                (
                    "numero_autorizacion",
                    models.CharField(blank=True, max_length=49, null=True),
                ),
                ("fecha_autorizacion", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("CREADO", "Creado (Pendiente Firma)"),
                            ("FIRMADO", "Firmado (Pendiente Envío)"),
                            ("RECIBIDO", "Recibido por SRI"),
                            ("DEVUELTO", "Devuelto por SRI (Error)"),
                            ("AUTORIZADO", "Autorizado"),
                            ("RECHAZADO", "Rechazado"),
                            ("ERROR", "Error Interno"),
                        ],
                        default="CREADO",
                        max_length=20,
                    ),
                ),
                (
                    "ambiente",
                    models.IntegerField(choices=[(1, "Pruebas"), (2, "Producción")]),
                ),
                (
                    "xml_generado",
                    models.FileField(
                        blank=True, null=True, upload_to="sri/xml/generados/"
                    ),
                ),
                (
                    "xml_firmado",
                    models.FileField(
                        blank=True, null=True, upload_to="sri/xml/firmados/"
                    ),
                ),
                (
                    "pdf_ride",
                    models.FileField(blank=True, null=True, upload_to="sri/pdf/"),
                ),
                ("mensajes_sri", models.JSONField(blank=True, default=list)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "punto_emision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="electronic_invoicing.puntoemision",
                    ),
                ),
                (
                    "venta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comprobante_electronico",
                        to="sales_management.venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comprobante Electrónico",
                "verbose_name_plural": "Comprobantes Electrónicos",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
