# Generated by Django 4.2.7 on 2026-04-07 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("electronic_invoicing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comprobanteelectronico",
            options={
                "ordering": ["-fecha_registro"],
                "verbose_name": "Comprobante Electrónico",
                "verbose_name_plural": "Comprobantes Electrónicos",
            },
        ),
        migrations.RenameField(
            model_name="comprobanteelectronico",
            old_name="fecha_creacion",
            new_name="fecha_registro",
        ),
        migrations.RemoveField(
            model_name="certificadodigital",
            name="password",
        ),
        migrations.RemoveField(
            model_name="comprobanteelectronico",
            name="mensajes_sri",
        ),
        migrations.RemoveField(
            model_name="comprobanteelectronico",
            name="pdf_ride",
        ),
        migrations.AddField(
            model_name="certificadodigital",
            name="password_encrypted",
            field=models.CharField(
                default=1, max_length=500, verbose_name="Password (Encriptado)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comprobanteelectronico",
            name="mensajes_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comprobanteelectronico",
            name="tipo_comprobante",
            field=models.CharField(
                default="01",
                help_text="01=Factura, 04=Nota de Crédito, etc.",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="comprobanteelectronico",
            name="xml_autorizado",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comprobanteelectronico",
            name="ambiente",
            field=models.IntegerField(
                choices=[(1, "Pruebas"), (2, "Producción")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="comprobanteelectronico",
            name="punto_emision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="electronic_invoicing.puntoemision",
            ),
        ),
        migrations.AlterField(
            model_name="comprobanteelectronico",
            name="xml_firmado",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comprobanteelectronico",
            name="xml_generado",
            field=models.TextField(blank=True, null=True),
        ),
    ]
