# Generated by Django 4.2.7 on 2026-04-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("electronic_invoicing", "0002_alter_comprobanteelectronico_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="puntoemision",
            name="ultimo_secuencial",
            field=models.IntegerField(
                default=0, help_text="El próximo comprobante será este número + 1"
            ),
        ),
    ]
