# Generated by Django 4.2.7 on 2026-04-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("electronic_invoicing", "0003_puntoemision_ultimo_secuencial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificadodigital",
            name="emisor",
            field=models.CharField(
                blank=True, editable=False, max_length=300, null=True
            ),
        ),
        migrations.AddField(
            model_name="certificadodigital",
            name="nombre_titular",
            field=models.CharField(
                blank=True, editable=False, max_length=300, null=True
            ),
        ),
        migrations.AddField(
            model_name="certificadodigital",
            name="ruc_titular",
            field=models.CharField(
                blank=True, editable=False, max_length=13, null=True
            ),
        ),
        migrations.AddField(
            model_name="sriconfig",
            name="wsdl_autorizacion_produccion",
            field=models.URLField(
                default="https://cel.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl",
                help_text="URL WSDL Autorización (Producción)",
            ),
        ),
        migrations.AddField(
            model_name="sriconfig",
            name="wsdl_autorizacion_pruebas",
            field=models.URLField(
                default="https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl",
                help_text="URL WSDL Autorización (Pruebas)",
            ),
        ),
        migrations.AddField(
            model_name="sriconfig",
            name="wsdl_recepcion_produccion",
            field=models.URLField(
                default="https://cel.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl",
                help_text="URL WSDL Recepción (Producción)",
            ),
        ),
        migrations.AddField(
            model_name="sriconfig",
            name="wsdl_recepcion_pruebas",
            field=models.URLField(
                default="https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl",
                help_text="URL WSDL Recepción (Pruebas)",
            ),
        ),
        migrations.AlterField(
            model_name="certificadodigital",
            name="fecha_vencimiento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
