# Generated by Django 4.2.7 on 2026-04-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("electronic_invoicing", "0004_certificadodigital_emisor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comprobanteelectronico",
            name="pdf_ride",
            field=models.FileField(blank=True, null=True, upload_to="sri/rides/"),
        ),
    ]
