# Generated by Django 4.2.7 on 2026-04-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("electronic_invoicing", "0005_comprobanteelectronico_pdf_ride"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificadodigital",
            name="emisor",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="certificadodigital",
            name="nombre_titular",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="certificadodigital",
            name="ruc_titular",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
