# Generated by Django 4.2.7 on 2026-05-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("electronic_invoicing", "0006_alter_certificadodigital_emisor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comprobanteelectronico",
            name="email_enviado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="comprobanteelectronico",
            name="error_email",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comprobanteelectronico",
            name="fecha_envio_email",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
