# Generated by Django 4.2.7 on 2025-10-02 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertaStock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_alerta",
                    models.CharField(
                        choices=[
                            ("STOCK_BAJO", "Stock Bajo"),
                            ("STOCK_CRITICO", "Stock Crítico"),
                            ("STOCK_AGOTADO", "Stock Agotado"),
                            ("QUINTAL_CRITICO", "Quintal Crítico"),
                            ("QUINTAL_AGOTADO", "Quintal Agotado"),
                            ("VENCIMIENTO_PROXIMO", "Vencimiento Próximo"),
                            ("PRODUCTO_VENCIDO", "Producto Vencido"),
                            ("REORDEN_NECESARIO", "Reorden Necesario"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("MEDIA", "Media"),
                            ("ALTA", "Alta"),
                            ("CRITICA", "Crítica"),
                        ],
                        db_index=True,
                        default="MEDIA",
                        max_length=10,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("VISTA", "Vista"),
                            ("EN_PROCESO", "En Proceso"),
                            ("RESUELTA", "Resuelta"),
                            ("IGNORADA", "Ignorada"),
                        ],
                        db_index=True,
                        default="PENDIENTE",
                        max_length=15,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensaje", models.TextField()),
                ("datos_adicionales", models.JSONField(blank=True, default=dict)),
                ("resuelta", models.BooleanField(db_index=True, default=False)),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("fecha_vista", models.DateTimeField(blank=True, null=True)),
                ("fecha_resolucion", models.DateTimeField(blank=True, null=True)),
                ("notas", models.TextField(blank=True)),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to="inventory_management.producto",
                    ),
                ),
                (
                    "producto_normal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to="inventory_management.productonormal",
                    ),
                ),
                (
                    "quintal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to="inventory_management.quintal",
                    ),
                ),
                (
                    "usuario_asignado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertas_asignadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_resolutor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertas_resueltas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta de Stock",
                "verbose_name_plural": "Alertas de Stock",
                "ordering": ["-prioridad", "-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionAlerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "umbral_stock_critico",
                    models.IntegerField(
                        default=5, help_text="Cantidad para considerar stock crítico"
                    ),
                ),
                (
                    "umbral_stock_bajo",
                    models.IntegerField(
                        default=10, help_text="Cantidad para considerar stock bajo"
                    ),
                ),
                (
                    "umbral_quintal_critico",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Porcentaje restante para considerar quintal crítico",
                        max_digits=5,
                    ),
                ),
                (
                    "dias_vencimiento_proximo",
                    models.IntegerField(
                        default=7, help_text="Días para considerar vencimiento próximo"
                    ),
                ),
                ("notificar_email", models.BooleanField(default=True)),
                ("notificar_push", models.BooleanField(default=False)),
                ("notificar_sms", models.BooleanField(default=False)),
                (
                    "emails_notificacion",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de emails para notificaciones",
                    ),
                ),
                (
                    "alertas_activas",
                    models.BooleanField(
                        default=True, help_text="Sistema de alertas activo"
                    ),
                ),
                (
                    "auto_generar_alertas",
                    models.BooleanField(
                        default=True, help_text="Generar alertas automáticamente"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración de Alertas",
                "verbose_name_plural": "Configuraciones de Alertas",
            },
        ),
        migrations.CreateModel(
            name="HistorialAlerta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("accion", models.CharField(max_length=50)),
                ("descripcion", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("datos_adicionales", models.JSONField(blank=True, default=dict)),
                (
                    "alerta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="stock_alert_system.alertastock",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Alerta",
                "verbose_name_plural": "Historiales de Alertas",
                "ordering": ["-fecha"],
            },
        ),
        migrations.AddIndex(
            model_name="alertastock",
            index=models.Index(
                fields=["tipo_alerta", "resuelta"],
                name="stock_alert_tipo_al_fa2483_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertastock",
            index=models.Index(
                fields=["prioridad", "estado"], name="stock_alert_priorid_914114_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertastock",
            index=models.Index(
                fields=["fecha_creacion", "resuelta"],
                name="stock_alert_fecha_c_2028b6_idx",
            ),
        ),
    ]
