# Generated by Django 4.2.7 on 2025-10-09 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logacceso",
            name="tipo_evento",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Inicio de sesión"),
                    ("LOGOUT", "Cierre de sesión"),
                    ("LOGIN_FAILED", "Intento de inicio fallido"),
                    ("PASSWORD_CHANGE", "Cambio de contraseña"),
                    ("ACCOUNT_LOCKED", "Cuenta bloqueada"),
                    ("PERMISSION_DENIED", "Permiso denegado"),
                    ("USER_CREATED", "Usuario creado"),
                    ("USER_UPDATED", "Usuario actualizado"),
                    ("USER_DELETED", "Usuario eliminado"),
                    ("USER_BLOCKED", "Usuario bloqueado"),
                    ("USER_UNBLOCKED", "Usuario desbloqueado"),
                    ("PERMISSION_CREATED", "Permiso creado"),
                    ("PERMISSION_DELETED", "Permiso eliminado"),
                    ("SESSION_CLOSED", "Sesión cerrada"),
                    ("ROL_CREATED", "Rol creado"),
                    ("ROL_UPDATED", "Rol actualizado"),
                    ("ROL_DELETED", "Rol eliminado"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarios",
                to="authentication.rol",
                verbose_name="Rol",
            ),
        ),
    ]
