# Generated by Django 4.2.7 on 2025-09-30 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Caja",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre de la caja (ej: Caja 1, Caja POS)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código único (ej: CJA-001)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PRINCIPAL", "Caja Principal"),
                            ("SECUNDARIA", "Caja Secundaria"),
                        ],
                        default="PRINCIPAL",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ABIERTA", "🟢 Abierta - Operativa"),
                            ("CERRADA", "🔴 Cerrada - Inactiva"),
                        ],
                        db_index=True,
                        default="CERRADA",
                        max_length=20,
                    ),
                ),
                (
                    "monto_apertura",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monto inicial al abrir caja",
                        max_digits=10,
                    ),
                ),
                (
                    "monto_actual",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monto actual en caja",
                        max_digits=10,
                    ),
                ),
                (
                    "fecha_apertura",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora de la última apertura",
                        null=True,
                    ),
                ),
                (
                    "fecha_cierre",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora del último cierre",
                        null=True,
                    ),
                ),
                (
                    "requiere_autorizacion_cierre",
                    models.BooleanField(
                        default=False,
                        help_text="Si requiere autorización de supervisor para cerrar",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True, help_text="Si la caja está activa en el sistema"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario_apertura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cajas_abiertas_por",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_cierre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cajas_cerradas_por",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Caja",
                "verbose_name_plural": "Cajas",
                "db_table": "fin_caja",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="CajaChica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre de la caja chica (ej: Caja Chica Tienda)",
                        max_length=100,
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código único (ej: CCH-001)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "monto_fondo",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto fijo del fondo de caja chica",
                        max_digits=10,
                    ),
                ),
                (
                    "monto_actual",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Saldo actual disponible",
                        max_digits=10,
                    ),
                ),
                (
                    "limite_gasto_individual",
                    models.DecimalField(
                        decimal_places=2,
                        default=50,
                        help_text="Límite máximo por gasto individual",
                        max_digits=10,
                    ),
                ),
                (
                    "umbral_reposicion",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cuando el saldo baja de este monto, se debe reponer",
                        max_digits=10,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVA", "🟢 Activa"), ("INACTIVA", "🔴 Inactiva")],
                        default="ACTIVA",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "fecha_ultima_reposicion",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cajas_chicas_responsable",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Caja Chica",
                "verbose_name_plural": "Cajas Chicas",
                "db_table": "fin_caja_chica",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="ArqueoCaja",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "numero_arqueo",
                    models.CharField(
                        help_text="Número único del arqueo (ARQ-2025-00001)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "fecha_apertura",
                    models.DateTimeField(help_text="Fecha de apertura de esta sesión"),
                ),
                (
                    "fecha_cierre",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Fecha de cierre"
                    ),
                ),
                (
                    "monto_apertura",
                    models.DecimalField(
                        decimal_places=2, help_text="Monto de apertura", max_digits=10
                    ),
                ),
                (
                    "total_ventas",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total de ventas del período",
                        max_digits=10,
                    ),
                ),
                (
                    "total_ingresos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total de ingresos adicionales",
                        max_digits=10,
                    ),
                ),
                (
                    "total_retiros",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total de retiros",
                        max_digits=10,
                    ),
                ),
                (
                    "monto_esperado",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto que debería haber en caja según el sistema",
                        max_digits=10,
                    ),
                ),
                (
                    "monto_contado",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto real contado en efectivo",
                        max_digits=10,
                    ),
                ),
                ("billetes_100", models.IntegerField(default=0)),
                ("billetes_50", models.IntegerField(default=0)),
                ("billetes_20", models.IntegerField(default=0)),
                ("billetes_10", models.IntegerField(default=0)),
                ("billetes_5", models.IntegerField(default=0)),
                ("billetes_1", models.IntegerField(default=0)),
                (
                    "monedas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "diferencia",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="monto_contado - monto_esperado (+ sobrante, - faltante)",
                        max_digits=10,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("CUADRADO", "✅ Cuadrado - Sin diferencias"),
                            ("SOBRANTE", "➕ Sobrante - Más efectivo del esperado"),
                            ("FALTANTE", "➖ Faltante - Menos efectivo del esperado"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "observaciones_diferencia",
                    models.TextField(
                        blank=True, help_text="Explicación de la diferencia si existe"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "caja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arqueos",
                        to="financial_management.caja",
                    ),
                ),
                (
                    "usuario_apertura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arqueos_abiertos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_cierre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arqueos_cerrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Arqueo de Caja",
                "verbose_name_plural": "Arqueos de Caja",
                "db_table": "fin_arqueo_caja",
                "ordering": ["-fecha_cierre"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoCajaChica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[
                            ("APERTURA", "🔓 Apertura de caja chica"),
                            ("GASTO", "💸 Gasto"),
                            ("REPOSICION", "➕ Reposición de fondo"),
                            ("AJUSTE", "⚙️ Ajuste"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "categoria_gasto",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LIMPIEZA", "🧹 Limpieza y aseo"),
                            ("OFICINA", "📎 Materiales de oficina"),
                            ("MANTENIMIENTO", "🔧 Mantenimiento menor"),
                            ("TRANSPORTE", "🚗 Transporte y combustible"),
                            ("ALIMENTACION", "🍔 Alimentación"),
                            ("EMERGENCIA", "🚨 Emergencia"),
                            ("OTRO", "📦 Otro"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "saldo_anterior",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("saldo_nuevo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descripcion", models.TextField()),
                (
                    "numero_comprobante",
                    models.CharField(
                        blank=True,
                        help_text="Número de factura o comprobante",
                        max_length=50,
                    ),
                ),
                (
                    "comprobante_adjunto",
                    models.FileField(
                        blank=True,
                        help_text="Foto o escaneo del comprobante",
                        null=True,
                        upload_to="cajas_chicas/comprobantes/",
                    ),
                ),
                (
                    "fecha_movimiento",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "caja_chica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="financial_management.cajachica",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Caja Chica",
                "verbose_name_plural": "Movimientos de Caja Chica",
                "db_table": "fin_movimiento_caja_chica",
                "ordering": ["-fecha_movimiento"],
                "indexes": [
                    models.Index(
                        fields=["caja_chica", "-fecha_movimiento"],
                        name="fin_movimie_caja_ch_e89cfb_idx",
                    ),
                    models.Index(
                        fields=["tipo_movimiento", "-fecha_movimiento"],
                        name="fin_movimie_tipo_mo_8b7487_idx",
                    ),
                    models.Index(
                        fields=["categoria_gasto", "-fecha_movimiento"],
                        name="fin_movimie_categor_34e281_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MovimientoCaja",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[
                            ("APERTURA", "🔓 Apertura de caja"),
                            ("CIERRE", "🔒 Cierre de caja"),
                            ("VENTA", "💰 Venta"),
                            ("INGRESO", "➕ Ingreso adicional"),
                            ("RETIRO", "➖ Retiro de efectivo"),
                            ("DEVOLUCION", "↩️ Devolución a cliente"),
                            ("AJUSTE_POSITIVO", "➕ Ajuste positivo"),
                            ("AJUSTE_NEGATIVO", "➖ Ajuste negativo"),
                            ("TRANSFERENCIA_ENTRADA", "📥 Transferencia recibida"),
                            ("TRANSFERENCIA_SALIDA", "📤 Transferencia enviada"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto del movimiento",
                        max_digits=10,
                    ),
                ),
                (
                    "saldo_anterior",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Saldo antes del movimiento",
                        max_digits=10,
                    ),
                ),
                (
                    "saldo_nuevo",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Saldo después del movimiento",
                        max_digits=10,
                    ),
                ),
                (
                    "fecha_movimiento",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "caja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="financial_management.caja",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_caja",
                        to="sales_management.venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Caja",
                "verbose_name_plural": "Movimientos de Caja",
                "db_table": "fin_movimiento_caja",
                "ordering": ["-fecha_movimiento"],
                "indexes": [
                    models.Index(
                        fields=["caja", "-fecha_movimiento"],
                        name="fin_movimie_caja_id_fd173a_idx",
                    ),
                    models.Index(
                        fields=["tipo_movimiento", "-fecha_movimiento"],
                        name="fin_movimie_tipo_mo_751287_idx",
                    ),
                    models.Index(
                        fields=["usuario", "-fecha_movimiento"],
                        name="fin_movimie_usuario_60aed2_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="caja",
            index=models.Index(fields=["codigo"], name="fin_caja_codigo_a2318d_idx"),
        ),
        migrations.AddIndex(
            model_name="caja",
            index=models.Index(
                fields=["estado", "activa"], name="fin_caja_estado_10d45a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="arqueocaja",
            index=models.Index(
                fields=["numero_arqueo"], name="fin_arqueo__numero__c2ee84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="arqueocaja",
            index=models.Index(
                fields=["caja", "-fecha_cierre"], name="fin_arqueo__caja_id_bd5ac6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="arqueocaja",
            index=models.Index(
                fields=["estado", "-fecha_cierre"], name="fin_arqueo__estado_f5e593_idx"
            ),
        ),
    ]
